[package]
name = "todo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.8", features = ["unstable-doc"] }
env_logger = "0.10.1"
log = "0.4.20"
persy = "1.4.5"
thiserror = "1.0.50"
